version: "3.9"

services:

  # Zookeeper - необходим для работы Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app_network

  # Kafka - брокер сообщений
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - app_network

  # Elasticsearch - хранилище логов
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    stdin_open: true
    tty: true
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Logstash - обработка и отправка логов в Elasticsearch
  logstash:
    container_name: logstash
    image: logstash:7.17.18
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Kibana - интерфейс для просмотра логов
  kibana:
    container_name: kibana
    image: kibana:7.17.18
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  # Filebeat - сборщик логов с контейнеров
  filebeat:
    user: root
    container_name: filebeat
    image: elastic/filebeat:7.17.18
    links:
      - logstash:logstash
    depends_on:
      - logstash
      - app
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - ./auth_service/logs:/usr/share/filebeat/mylogs
      - ./product_service/logs:/usr/share/filebeat/mylogs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: [ "--strict.perms=false" ]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    networks:
      - app_network
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"

  db_auth:
    image: postgres:12-bullseye
    container_name: postgres_auth_db
    environment:
      POSTGRES_USER: storage_admin # Задать пользователя
      POSTGRES_PASSWORD: THw7l0bxvPPkWUhP # Задать пароль
      POSTGRES_DB: strg_users_db # Задать имя БД
    ports:
      - "5435:5432" # Открыть порт для внешнего доступа
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./auth_service/db_init/init.sql:/docker-entrypoint-initdb.d/init.sql # Путь к папке с SQL-скриптами
    networks:
      - app_network

  db_products:
    image: postgres:12-bullseye
    container_name: postgres_products_db
    environment:
      POSTGRES_USER: storage_admin # Задать пользователя
      POSTGRES_PASSWORD: THw7l0bxvPPkWUhP # Задать пароль
      POSTGRES_DB: strg_products_db # Задать имя БД
    ports:
      - "5435:5432" # Открыть порт для внешнего доступа
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
      - ./product_service/db_init/init_products.sql:/docker-entrypoint-initdb.d/init.sql # Путь к папке с SQL-скриптами
    networks:
      - app_network

  auth_service:
    build:
      context: ./auth_service # Путь к папке с кодом приложения
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - ./auth_service/logs:/app/logs
    depends_on:
      - db_auth
    environment:
      DATABASE_URL: postgresql://storage_admin:THw7l0bxvPPkWUhP@db:5432/strg_users_db
    ports:
      - "8001:8000" # Открыть порт для FastAPI или другого веб-сервиса
    networks:
      - app_network

  products_service:
    build:
      context: ./products_service
      dockerfile: Dockerfile
    container_name: products_service
    volumes:
      - ./products_service/logs:/app/logs
    depends_on:
      - db_products
    environment:
      DATABASE_URL: postgresql://storage_admin:THw7l0bxvPPkWUhP@db_products:5432/strg_products_db
    ports:
      - "8002:8000" # Открываем порт для сервиса продуктов
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
